name: Update GPI Leaderboard

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run scraper script
        run: python .github/scripts/scrape_gpi.py

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add top30.json
          git commit -m "Auto update top30.json" || echo "No changes"
          git push
